# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTestSetting' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoTestSetting
  pod 'JTTestSetting',:path=>'../'
  pod 'YYCache'
  pod 'MJExtension','3.0.15.1'
  pod 'Masonry'
  pod 'UITableView+FDTemplateLayoutCell'
  
  target 'DemoTestSettingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoTestSettingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
